# ----------------------------
# Project information
# ----------------------------
site_name: The Very Simple List of Agentforce Best Practices
site_description: A curated collection of practical patterns and principles for designing and delivering Agentforce solutions that create measurable business value.
site_author: Luke Bottomley
site_url: https://botbot-priv.github.io/the-very-simple-list-of-agentforce-best-practices/

# ----------------------------
# Theme and features
# ----------------------------
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.action.edit
  palette:
    primary: indigo
    accent: blue
  icon:
    repo: fontawesome/brands/github

# ----------------------------
# Repository & edit links
# ----------------------------
repo_url: https://github.com/botbot-priv/the-very-simple-list-of-agentforce-best-practices
repo_name: the-very-simple-list-of-agentforce-best-practices
edit_uri: edit/main/docs/

# ----------------------------
# Navigation
# ----------------------------
nav:
  - Home: index.md
  - Principles: principles.md
  - Design Patterns: design-patterns.md
  - Evaluation & ROI: evaluation.md
  - Examples: examples.md

# ----------------------------
# Plugins
# ----------------------------
plugins:
  - search

# ----------------------------
# Extra / footer
# ----------------------------
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/botbot-priv/the-very-simple-list-of-agentforce-best-practices
  generator: false

copyright: >
  © 2025 Luke Bottomley — content licensed under
  <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener">
  CC BY 4.0 International</a>.<br>
  You’re free to reuse it as long as you give credit to
  <strong>Luke Bottomley — The Very Simple List of Agentforce Best Practices</strong>.
